# Generated by Django 4.0.6 on 2022-08-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='typejob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='mainapp.jobtype'),
        ),
    ]
