# Generated by Django 4.0.6 on 2022-08-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_alter_job_typejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_time', models.DateField(auto_now=True)),
                ('assignment_status', models.CharField(choices=[('assigned', 'assigned'), ('in_progress', 'in_progress'), ('unassigned', 'unassigned'), ('completed', 'completed')], default='assigned', max_length=250)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignperson', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='assign_job_author', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idofjob', to='mainapp.job')),
            ],
        ),
    ]
